#!/bin/bash

# generate 8 numbers into file 'numbers'
dd if=/dev/random bs=1 count=8 of=numbers 2> /dev/null

# compile project
#mpic++ --prefix /usr/local/share/OpenMPI -o oems oems.cpp

# run ptoject
#mpirun --prefix /usr/local/share/OpenMPI -np $numbers oems

# clean
rm -f oems numbers
