#!/bin/bash

# generate 8 numbers into file 'numbers'
dd if=/dev/random bs=1 count=8 of=numbers 2> /dev/null

# compile project
mpicc --prefix /usr/local/share/OpenMPI -o oems oems.c

# run project
mpirun --prefix /usr/local/share/OpenMPI -oversubscribe -np 20 oems

# clean
rm -f oems numbers
